collections:
  authors:
    output: true
  themes:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl: /online

gems:
  - jekyll-paginate-v2

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-redirect-from

pagination:
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
